# Generated by Django 3.2.5 on 2021-07-27 20:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chPropios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proveedor',
            options={'ordering': ['nombre'], 'verbose_name_plural': 'Proveedores'},
        ),
        migrations.RemoveField(
            model_name='chpropio',
            name='situacion',
        ),
        migrations.AlterField(
            model_name='chpropio',
            name='fechaCarga',
            field=models.DateField(default=datetime.datetime(2021, 7, 27, 17, 17, 38, 312567)),
        ),
    ]
