# Generated by Django 3.2.5 on 2021-07-28 21:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chPropios', '0002_auto_20210727_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chpropio',
            name='fechaCarga',
            field=models.DateField(default=datetime.datetime(2021, 7, 28, 18, 49, 38, 807547)),
        ),
        migrations.AlterField(
            model_name='chpropio',
            name='numCh',
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
