# Generated by Django 3.2.5 on 2021-08-01 01:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chPropios', '0003_auto_20210728_1849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chpropio',
            name='banco',
            field=models.CharField(choices=[('CREDICOOP', 'CREDICOOP'), ('HSBC', 'HSBC'), ('MACRO', 'MACRO')], max_length=50),
        ),
        migrations.AlterField(
            model_name='chpropio',
            name='fechaCarga',
            field=models.DateField(default=datetime.datetime(2021, 7, 31, 22, 55, 9, 220546)),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='cuit',
            field=models.CharField(blank=True, max_length=11),
        ),
    ]
