# Generated by Django 3.2.5 on 2021-08-01 17:38

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proveedor', '0001_initial'),
        ('chPropios', '0004_auto_20210731_2255'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chpropio',
            options={'ordering': ['monto'], 'verbose_name': 'Cheque Propio', 'verbose_name_plural': 'Cheques Propios'},
        ),
        migrations.AlterField(
            model_name='chpropio',
            name='fechaCarga',
            field=models.DateField(default=datetime.datetime(2021, 8, 1, 14, 38, 23, 287517)),
        ),
        migrations.AlterField(
            model_name='chpropio',
            name='proveedor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='proveedor.proveedor'),
        ),
        migrations.DeleteModel(
            name='Proveedor',
        ),
    ]
