# Generated by Django 3.2.5 on 2021-08-01 17:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chPropios', '0005_auto_20210801_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chpropio',
            name='fechaCarga',
            field=models.DateField(default=datetime.datetime(2021, 8, 1, 14, 48, 10, 85453)),
        ),
    ]
