# Generated by Django 3.1.2 on 2021-08-08 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chPropios', '0011_auto_20210808_1713'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='chpropio',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='chpropio',
            constraint=models.UniqueConstraint(fields=('banco', 'numCh'), name='name of constraint'),
        ),
    ]
