# Generated by Django 3.1.2 on 2021-08-27 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chPropios', '0012_auto_20210808_1807'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='chpropio',
            name='name of constraint',
        ),
        migrations.AddConstraint(
            model_name='chpropio',
            constraint=models.UniqueConstraint(fields=('banco', 'numCh'), name='Cheque unico'),
        ),
    ]
