# Generated by Django 3.1.2 on 2021-08-27 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Empresa', '0001_initial'),
        ('chPropios', '0013_auto_20210827_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='chpropio',
            name='empresa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Empresa.empresa'),
        ),
    ]
