# Generated by Django 3.1.2 on 2021-08-27 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Empresa', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='user',
        ),
    ]
