# Generated by Django 3.1.2 on 2021-08-27 19:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Empresa', '0002_remove_empresa_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
